# Generated by Django 3.1.3 on 2021-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=300)),
                ('usia', models.CharField(blank=True, max_length=150)),
                ('profesi', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
